spring.application.name=config-service
server.port=9999
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.server.git.uri=file:///C:/Users/Koussay/Desktop/moataz/Spring/proj/config-repo
spring.cloud.config.server.git.default-label=master
#spring.cloud.discovery.enabled=true


##NB: RUNNI DISCOVERY BAAED GATEAWAY BAAED CONFIG BAAED CUSTOMER BAAED ACCOUNT